<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.2.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TekProvider.Application\TekProvider.Application.csproj" />
    <ProjectReference Include="..\TekProvider.Infrastructure\TekProvider.Infrastructure.csproj" />
  </ItemGroup>

</Project>
